nohup: ignoring input
 * Serving Flask app 'main_swagger'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://84.247.171.243:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 111-054-978
[2025-08-14 00:16:53,164] ERROR in app: Exception on /api/avaliacoes [POST]
Traceback (most recent call last):
  File "/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py", line 145, in post
    api.abort(400, f'Campo obrigat√≥rio em falta: {campo}')
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/helpers.py", line 284, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/werkzeug/exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py", line 155, in post
    api.abort(500, f'Erro ao criar avalia√ß√£o: {str(e)}')
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/helpers.py", line 284, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/werkzeug/exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
87.58.94.76 - - [14/Aug/2025 00:16:53] "[35m[1mPOST /api/avaliacoes HTTP/1.1[0m" 500 -
87.58.94.76 - - [14/Aug/2025 00:17:02] "GET /docs/ HTTP/1.1" 200 -
87.58.94.76 - - [14/Aug/2025 00:17:02] "[36mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:17:02] "[36mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:17:02] "[36mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:17:02] "[36mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:17:02] "GET /api/swagger.json HTTP/1.1" 200 -
87.58.94.76 - - [14/Aug/2025 00:17:02] "[36mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:17:14] "GET /api/avaliacoes?per_page=10&page=1 HTTP/1.1" 200 -
[2025-08-14 00:17:32,841] ERROR in app: Exception on /api/avaliacoes [POST]
Traceback (most recent call last):
  File "/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py", line 145, in post
    api.abort(400, f'Campo obrigat√≥rio em falta: {campo}')
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/helpers.py", line 284, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/werkzeug/exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py", line 155, in post
    api.abort(500, f'Erro ao criar avalia√ß√£o: {str(e)}')
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/flask/helpers.py", line 284, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/kcabral/disaster-assessment-api/daa_venv/lib/python3.12/site-packages/werkzeug/exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
87.58.94.76 - - [14/Aug/2025 00:17:32] "[35m[1mPOST /api/avaliacoes HTTP/1.1[0m" 500 -
 * Detected change in '/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 111-054-978
127.0.0.1 - - [14/Aug/2025 00:18:28] "[33mGET / HTTP/1.1[0m" 404 -
127.0.0.1 - - [14/Aug/2025 00:18:37] "[33mGET /api/avaliacoes/ HTTP/1.1[0m" 404 -
 * Detected change in '/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 111-054-978
 * Detected change in '/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 111-054-978
 * Detected change in '/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 111-054-978
 * Detected change in '/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 111-054-978
 * Detected change in '/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 111-054-978
127.0.0.1 - - [14/Aug/2025 00:20:35] "[35m[1mPOST /api/avaliacoes HTTP/1.1[0m" 201 -
87.58.94.76 - - [14/Aug/2025 00:21:07] "[31m[1mPOST /api/avaliacoes HTTP/1.1[0m" 400 -
197.255.134.58 - - [14/Aug/2025 00:24:34] "GET /docs/ HTTP/1.1" 200 -
197.255.134.58 - - [14/Aug/2025 00:24:34] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
197.255.134.58 - - [14/Aug/2025 00:24:34] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
197.255.134.58 - - [14/Aug/2025 00:24:34] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
197.255.134.58 - - [14/Aug/2025 00:24:34] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
38.44.66.233 - - [14/Aug/2025 00:24:35] "GET /docs/ HTTP/1.1" 200 -
38.44.66.233 - - [14/Aug/2025 00:24:35] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
38.44.66.233 - - [14/Aug/2025 00:24:35] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
38.44.66.233 - - [14/Aug/2025 00:24:35] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
38.44.66.233 - - [14/Aug/2025 00:24:35] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
197.255.134.58 - - [14/Aug/2025 00:24:35] "GET /api/swagger.json HTTP/1.1" 200 -
197.255.134.58 - - [14/Aug/2025 00:24:35] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
38.44.66.233 - - [14/Aug/2025 00:24:38] "GET /api/swagger.json HTTP/1.1" 200 -
87.58.94.76 - - [14/Aug/2025 00:26:14] "[31m[1mPOST /api/avaliacoes HTTP/1.1[0m" 400 -
37.28.234.255 - - [14/Aug/2025 00:29:50] "GET /docs/ HTTP/1.1" 200 -
37.28.234.255 - - [14/Aug/2025 00:29:50] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
37.28.234.255 - - [14/Aug/2025 00:29:50] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
37.28.234.255 - - [14/Aug/2025 00:29:50] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
37.28.234.255 - - [14/Aug/2025 00:29:50] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
37.28.234.255 - - [14/Aug/2025 00:29:51] "GET /api/swagger.json HTTP/1.1" 200 -
173.252.95.2 - - [14/Aug/2025 00:29:55] "GET /docs/ HTTP/1.1" 200 -
173.252.95.16 - - [14/Aug/2025 00:29:56] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
173.252.95.14 - - [14/Aug/2025 00:29:56] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
41.221.207.135 - - [14/Aug/2025 00:29:58] "GET /docs/ HTTP/1.1" 200 -
41.221.207.135 - - [14/Aug/2025 00:29:58] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
41.221.207.135 - - [14/Aug/2025 00:29:58] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
41.221.207.135 - - [14/Aug/2025 00:29:58] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
41.221.207.135 - - [14/Aug/2025 00:29:58] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
41.221.207.135 - - [14/Aug/2025 00:30:00] "GET /api/swagger.json HTTP/1.1" 200 -
41.221.207.135 - - [14/Aug/2025 00:30:00] "GET /swaggerui/favicon-16x16.png HTTP/1.1" 200 -
41.221.207.135 - - [14/Aug/2025 00:30:00] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2025 00:32:51] "[33mGET /api/ HTTP/1.1[0m" 404 -
127.0.0.1 - - [14/Aug/2025 00:32:51] "GET /docs/ HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2025 00:32:51] "GET /api/avaliacoes HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2025 00:32:51] "[35m[1mPOST /api/avaliacoes HTTP/1.1[0m" 201 -
127.0.0.1 - - [14/Aug/2025 00:32:51] "[31m[1mPOST /api/avaliacoes HTTP/1.1[0m" 400 -
 * Detected change in '/home/kcabral/disaster-assessment-api/src/routes/assessment_swagger.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 111-054-978
127.0.0.1 - - [14/Aug/2025 00:33:40] "[35m[1mPOST /api/avaliacoes HTTP/1.1[0m" 201 -
87.58.94.76 - - [14/Aug/2025 00:33:58] "GET /docs/ HTTP/1.1" 200 -
87.58.94.76 - - [14/Aug/2025 00:33:59] "[36mGET /swaggerui/droid-sans.css HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:33:59] "[36mGET /swaggerui/swagger-ui.css HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:33:59] "[36mGET /swaggerui/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:33:59] "[36mGET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:33:59] "GET /api/swagger.json HTTP/1.1" 200 -
87.58.94.76 - - [14/Aug/2025 00:33:59] "[36mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 304 -
87.58.94.76 - - [14/Aug/2025 00:34:06] "GET /api/avaliacoes?per_page=10&page=1 HTTP/1.1" 200 -
